.\" Manpage for huggle
.\" Contact benapetr@gmail.com for suggestions or questions
.TH man 1 "3.0.0.0" "huggle man page"
.SH NAME
huggle \- launch huggle
.SH SYNOPSIS
huggle [-vh]
.SH DESCRIPTION
Huggle is an antivandalism software for use on wikimedia projects. It requires X server to run.
.SH OPTIONS
Following options can be used to adjust huggle

 -h|--help:         Display help for program
 -v:                Increases verbosity, you can use multiple -vvvvvv parameters to make the verbosity level much higher
 --safe:            Start huggle in special mode where lot of stuff is skipped during load
 --dot:             Debug on terminal only mode, in this mode debug lines are only stored on terminal
 --syslog [file]:   Will write a logs to a file

.SH BUGS
See http://bugzilla.wikimedia.org/ for bug reports
.SH AUTHOR
See http://meta.wikimedia.org/Huggle/Members
